name: fishermen_safety
description: "Smart Fisherman Safety & Navigation System - A premium offline-first mobile lifeline."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management & Routing
  flutter_riverpod: ^2.4.9
  go_router: ^13.0.0

  # Local DB & Storage (Extreme Performance)
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # HTTP client
  dio: ^5.4.0

  # Location & Sensors
  geolocator: ^10.1.0

  # Mapping (OSM)
  flutter_map: ^6.1.0
  latlong2: ^0.9.0

  # Aesthetics & Visuals
  google_fonts: ^6.1.0
  flutter_animate: ^4.5.0
  uuid: ^4.3.3

  # Voice Assistant & Feedback
  flutter_tts: ^3.8.5
  speech_to_text: ^7.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
