export const localizedValues = {
  en: {
    appTitle: 'Smart Fisherman Safety',
    login: 'Login',
    register: 'Register',
    mobileNumber: 'Mobile Number',
    password: 'Password',
    fullName: 'Full Name',
    boatName: 'Boat Name',
    regNumber: 'Registration Number',
    harbor: 'Harbor Location',
    signup: 'Sign Up',
    signin: 'Sign In',
    sosButton: 'HOLD SOS FOR 3s',
    sosCountdown: 'SOS COUNTDOWN: ',
    sosTriggered: 'SOS TRIGGERED! Contacts notified.',
    borderWarning: 'BORDER WARNING! APPROACHING BORDER.',
    borderDistance: 'Border Proximity: ',
    speed: 'Speed',
    knots: 'knots',
    offlineSync: 'Offline mode. Queued payloads: ',
    profile: 'Profile',
    contacts: 'Emergency Contacts',
    settings: 'Settings',
    logout: 'Sign Out',
    map: 'Navigation Map',
    weather: 'Marine Weather',
    changeLanguage: 'Change Language',
  },
  ta: {
    appTitle: 'ஸ்மார்ட் மீனவர் பாதுகாப்பு',
    login: 'உள்நுழைய',
    register: 'பதிவு செய்ய',
    mobileNumber: 'அலைபேசி எண்',
    password: 'கடவுச்சொல்',
    fullName: 'முழு பெயர்',
    boatName: 'படகு பெயர்',
    regNumber: 'பதிவு எண்',
    harbor: 'துறைமுக இருப்பிடம்',
    signup: 'பதிவு செய்',
    signin: 'உள்நுழை',
    sosButton: '3 விநாடிகள் அழுത്തി பிடிக்கவும்',
    sosCountdown: 'SOS கவுண்ட்டவுன்: ',
    sosTriggered: 'SOS அனுப்பப்பட்டது! தொடர்பு கொள்ளப்பட்டது.',
    borderWarning: 'எல்லை எச்சரிக்கை! உடனே திரும்புங்கள்.',
    borderDistance: 'எல்லை அருகாமை: ',
    speed: 'வேகம்',
    knots: 'நாட்ஸ்',
    offlineSync: 'ஆஃப்லைன் பயன்முறை. வரிசையில் உள்ளது: ',
    profile: 'சுயவிவரம்',
    contacts: 'அவசர தொடர்புகள்',
    settings: 'அமைப்புகள்',
    logout: 'வெளியேறு',
    map: 'வரைபடம்',
    weather: 'கடல் வானிலை',
    changeLanguage: 'மொழியை மாற்று',
  },
  te: {
    appTitle: 'స్మార్ట్ మత్స్యకార రక్షణ',
    login: 'లాగిన్',
    register: 'నమోదు చేయండి',
    mobileNumber: 'మొబైల్ సంఖ్య',
    password: 'పాస్‌వర్డ్',
    fullName: 'పూర్తి పేరు',
    boatName: 'పడవ పేరు',
    regNumber: 'నమోదు సంఖ్య',
    harbor: 'హార్బర్ లొకేషన్',
    signup: 'సైన్ అప్',
    signin: 'సైన్ ఇన్',
    sosButton: 'SOS కోసం 3 సెకన్లు నొక్కండి',
    sosCountdown: 'SOS కౌంట్‌డౌన్: ',
    sosTriggered: 'SOS సక్రియం చేయబడింది!',
    borderWarning: 'సరిహద్దు హెచ్చరిక! వెంటనే వెనక్కి వెళ్ళండి.',
    borderDistance: 'సరిహద్దు దూరం: ',
    speed: 'వేగం',
    knots: 'నాట్స్',
    offlineSync: 'ఆఫ్‌లైన్ మోడ్. వేచి ఉంది: ',
    profile: 'ప్రొఫైల్',
    contacts: 'అవసరాల పరిచయాలు',
    settings: 'సెట్టింగ్స్',
    logout: 'సైన్ అవుట్',
    map: 'నావిగేషన్ మ్యాప్',
    weather: 'సముద్ర వాతావరణం',
    changeLanguage: 'భాషను మార్చండి',
  },
  kn: {
    appTitle: 'ಸ್ಮಾರ್ಟ್ ಮೀನುಗಾರರ ರಕ್ಷಣೆ',
    login: 'ಲಾಗಿನ್',
    register: 'ನೋಂದಣಿ',
    mobileNumber: 'ಮೊಬೈಲ್ ಸಂಖ್ಯೆ',
    password: 'ಪಾಸ್‌ವರ್ಡ್',
    fullName: 'ಪೂರ್ಣ ಹೆಸರು',
    boatName: 'ದೋಣಿ ಹೆಸರು',
    regNumber: 'ನೋಂದಣಿ ಸಂಖ್ಯೆ',
    harbor: 'ಬಂದರು ಸ್ಥಳ',
    signup: 'ಸೈನ್ ಅಪ್',
    signin: 'ಸೈನ್ ಇನ್',
    sosButton: 'SOS ಗಾಗಿ 3 ಸೆಕೆಂಡು ಒತ್ತಿ ಹಿಡಿಯಿರಿ',
    sosCountdown: 'SOS ಕೌಂಟ್‌ಡೌನ್: ',
    sosTriggered: 'SOS ಪ್ರಚೋದಿಸಲಾಗಿದೆ!',
    borderWarning: 'ಗಡಿ ಎಚ್ಚರಿಕೆ! ತಕ್ಷಣ ಹಿಂತಿರುಗಿ.',
    borderDistance: 'ಗಡಿ ಸಾಮೀಪ್ಯ: ',
    speed: 'ವೇಗ',
    knots: 'ನಾಟ್ಸ್',
    offlineSync: 'ಆಫ್‌ಲೈನ್ ಮೋಡ್. ಬಾಕಿ ಉಳಿದಿದೆ: ',
    profile: 'ಪ್ರೊಫೈಲ್',
    contacts: 'ತುರ್ತು ಸಂಪರ್ಕಗಳು',
    settings: 'ಸಂಯೋಜನೆಗಳು',
    logout: 'ಸೈನ್ ಔಟ್',
    map: 'ನಕ್ಷೆ',
    weather: 'ಹವಾಮಾನ',
    changeLanguage: 'ಭಾಷೆ ಬದಲಾಯಿಸಿ',
  },
  ml: {
    appTitle: 'സ്മാർട്ട് ഫിഷർമാൻ സേഫ്റ്റി',
    login: 'ലോഗിൻ',
    register: 'രജിസ്റ്റർ ചെയ്യുക',
    mobileNumber: 'മൊബൈൽ നമ്പർ',
    password: 'പാസ്‌വേഡ്',
    fullName: 'മുഴുവൻ പേര്',
    boatName: 'ബോട്ടിന്റെ പേര്',
    regNumber: 'രജിസ്ട്രേഷൻ നമ്പർ',
    harbor: 'ഹാർബർ ലൊക്കേഷൻ',
    signup: 'രജിസ്റ്റർ ചെയ്യുക',
    signin: 'ലോഗിн ചെയ്യുക',
    sosButton: 'SOS അമർത്തി പിടിക്കുക 3 സെക്കൻഡ്',
    sosCountdown: 'SOS കൗണ്ട്ഡൗൺ: ',
    sosTriggered: 'SOS അയച്ചു കഴിഞ്ഞു!',
    borderWarning: 'അതിർത്തി മുന്നറിയിപ്പ്! ഉടൻ മടങ്ങുക.',
    borderDistance: 'അതിർത്തിയിലേക്കുള്ള ദൂരം: ',
    speed: 'വേഗത',
    knots: 'നോട്ട്സ്',
    offlineSync: 'ഓഫ്‌ലൈൻ മോഡ്. ക്യൂവിലുള്ളവ: ',
    profile: 'പ്രൊഫൈൽ',
    contacts: 'അടിയന്തര കോൺടാക്റ്റുകൾ',
    settings: 'ക്രമീകരണങ്ങൾ',
    logout: 'ലോഗ് ഔട്ട്',
    map: 'മാപ്പ്',
    weather: 'കടൽ കാലാവസ്ഥ',
    changeLanguage: 'ഭാഷ മാറ്റുക',
  },
  hi: {
    appTitle: 'स्मार्ट मछुआरा सुरक्षा',
    login: 'लॉगिन',
    register: 'पंजीकरण',
    mobileNumber: 'मोबाइल नंबर',
    password: 'पासवर्ड',
    fullName: 'पूरा नाम',
    boatName: 'नाव का नाम',
    regNumber: 'पंजीकरण संख्या',
    harbor: 'बंदरगाह स्थान',
    signup: 'साइन अप',
    signin: 'साइन इन',
    sosButton: 'SOS के लिए 3 सेकंड दबाएं',
    sosCountdown: 'SOS काउंटडाउन: ',
    sosTriggered: 'SOS भेजा गया! संपर्क सूचित।',
    borderWarning: 'सीमा चेतावनी! तुरंत वापस जाएं।',
    borderDistance: 'सीमा दूरी: ',
    speed: 'गति',
    knots: 'नॉट',
    offlineSync: 'ऑफ़लाइन मोड। लंबित सिंक: ',
    profile: 'प्रोफ़ाइल',
    contacts: 'आपातकालीन संपर्क',
    settings: 'सेटिंग्स',
    logout: 'साइन आउट',
    map: 'नेविगेशन नक्शा',
    weather: 'समुद्री मौसम',
    changeLanguage: 'भाषा बदलें',
  }
};

export const translate = (key, lang = 'en') => {
  const currentLang = lang || 'en';
  if (!localizedValues[currentLang]) {
    return localizedValues['en'][key] || key;
  }
  return localizedValues[currentLang][key] || localizedValues['en'][key] || key;
};
